export const CITIES_BY_PROVINCE: Record<string, string[]> = {
  'Aceh': ['Banda Aceh', 'Langsa', 'Lhokseumawe', 'Sabang', 'Subulussalam', 'Aceh Besar', 'Pidie', 'Aceh Utara'],
  'Bali': ['Denpasar', 'Badung', 'Buleleng', 'Gianyar', 'Tabanan', 'Karangasem', 'Klungkung', 'Jembrana', 'Bangli'],
  'Banten': ['Tangerang', 'Tangerang Selatan', 'Cilegon', 'Serang', 'Pandeglang', 'Lebak'],
  'Bengkulu': ['Bengkulu', 'Rejang Lebong', 'Muko Muko', 'Kepahiang', 'Bengkulu Utara'],
  'D.I. Yogyakarta': ['Yogyakarta', 'Sleman', 'Bantul', 'Kulon Progo', 'Gunungkidul'],
  'D.K.I. Jakarta': ['Jakarta Pusat', 'Jakarta Barat', 'Jakarta Utara', 'Jakarta Timur', 'Jakarta Selatan', 'Kepulauan Seribu'],
  'Gorontalo': ['Gorontalo', 'Boalemo', 'Bone Bolango', 'Pohuwato'],
  'Jambi': ['Jambi', 'Sungai Penuh', 'Muaro Jambi', 'Bungo', 'Tebo', 'Kerinci'],
  'Jawa Barat': ['Bandung', 'Bekasi', 'Depok', 'Bogor', 'Tasikmalaya', 'Cimahi', 'Sukabumi', 'Cirebon', 'Banjar', 'Karawang', 'Garut', 'Subang', 'Sumedang', 'Purwakarta', 'Cianjur'],
  'Jawa Tengah': ['Semarang', 'Surakarta (Solo)', 'Salatiga', 'Pekalongan', 'Tegal', 'Magelang', 'Banyumas', 'Kudus', 'Cilacap', 'Klaten', 'Jepara', 'Brebes', 'Demak'],
  'Jawa Timur': ['Surabaya', 'Malang', 'Sidoarjo', 'Gresik', 'Kediri', 'Jember', 'Madiun', 'Batu', 'Pasuruan', 'Probolinggo', 'Blitar', 'Mojokerto', 'Banyuwangi', 'Tuban', 'Lamongan'],
  'Kalimantan Barat': ['Pontianak', 'Singkawang', 'Kubu Raya', 'Mempawah', 'Sambas', 'Ketapang'],
  'Kalimantan Selatan': ['Banjarmasin', 'Banjarbaru', 'Banjar', 'Tanah Laut', 'Barito Kuala'],
  'Kalimantan Tengah': ['Palangkaraya', 'Kotawaringin Timur', 'Kotawaringin Barat', 'Kapuas'],
  'Kalimantan Timur': ['Samarinda', 'Balikpapan', 'Bontang', 'Kutai Kartanegara', 'Kutai Timur', 'Berau'],
  'Kalimantan Utara': ['Tarakan', 'Bulungan', 'Nunukan', 'Malinau'],
  'Kepulauan Bangka Belitung': ['Pangkalpinang', 'Bangka', 'Belitung', 'Bangka Barat'],
  'Kepulauan Riau': ['Batam', 'Tanjungpinang', 'Bintan', 'Karimun', 'Natuna'],
  'Lampung': ['Bandar Lampung', 'Metro', 'Lampung Selatan', 'Lampung Tengah', 'Lampung Utara', 'Pringsewu'],
  'Maluku': ['Ambon', 'Tual', 'Maluku Tengah', 'Maluku Tenggara'],
  'Maluku Utara': ['Ternate', 'Tidore Kepulauan', 'Halmahera Utara', 'Halmahera Barat'],
  'Nusa Tenggara Barat': ['Mataram', 'Bima', 'Lombok Barat', 'Lombok Timur', 'Lombok Tengah', 'Sumbawa'],
  'Nusa Tenggara Timur': ['Kupang', 'Sikka', 'Ende', 'Flores Timur', 'Manggarai'],
  'Papua': ['Jayapura', 'Biak Numfor', 'Kepulauan Yapen', 'Keerom'],
  'Papua Barat': ['Manokwari', 'Fakfak', 'Kaimana', 'Teluk Wondama'],
  'Papua Barat Daya': ['Sorong', 'Raja Ampat', 'Sorong Selatan'],
  'Papua Pegunungan': ['Wamena (Jayawijaya)', 'Lanny Jaya', 'Tolikara'],
  'Papua Selatan': ['Merauke', 'Boven Digoel', 'Mappi'],
  'Papua Tengah': ['Nabire', 'Mimika (Timika)', 'Paniai'],
  'Riau': ['Pekanbaru', 'Dumai', 'Kampar', 'Bengkalis', 'Siak', 'Indragiri Hilir', 'Rokan Hulu'],
  'Sulawesi Barat': ['Mamuju', 'Majene', 'Polewali Mandar'],
  'Sulawesi Selatan': ['Makassar', 'Parepare', 'Palopo', 'Gowa', 'Maros', 'Bone', 'Bulukumba', 'Toraja'],
  'Sulawesi Tengah': ['Palu', 'Donggala', 'Poso', 'Banggai', 'Toli-Toli'],
  'Sulawesi Tenggara': ['Kendari', 'Baubau', 'Konawe', 'Kolaka', 'Muna'],
  'Sulawesi Utara': ['Manado', 'Bitung', 'Tomohon', 'Kotamobagu', 'Minahasa', 'Sangihe'],
  'Sumatera Barat': ['Padang', 'Bukittinggi', 'Payakumbuh', 'Solok', 'Pariaman', 'Padang Panjang', 'Sawahlunto', 'Pesisir Selatan'],
  'Sumatera Selatan': ['Palembang', 'Prabumulih', 'Lubuklinggau', 'Pagar Alam', 'Ogan Komering Ilir', 'Muara Enim', 'Banyuasin'],
  'Sumatera Utara': ['Medan', 'Binjai', 'Pematangsiantar', 'Tanjungbalai', 'Tebing Tinggi', 'Sibolga', 'Padangsidimpuan', 'Deli Serdang', 'Langkat', 'Karo', 'Asahan']
};

export const ALL_CITIES: string[] = Object.values(CITIES_BY_PROVINCE).flat().sort();
